manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/jsenjobs
  projects:
    - name: zmk
      remote: jsenjobs
      revision: qh
      import: app/west.yml
  self:
    path: config
